# Generated by Django 4.1.7 on 2023-03-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daawa', '0003_alter_sale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
